### ISSUE TITLE
Ussd start state without run function fails

### ISSUE THREAD

**Issue by AsetaShadrach** [Wanyeki/ussd-at#1]
Whenever I try this I get an error:
```
menu.startState({
    next: {
        '': function(){
            if(user){
                return 'userMenu';
            }
            else {
                return 'registerMenu';
            }
        }
    }
});
```

`Error TypeError : this.curr_state.run is not a function`

**Comment by Wanyeki** [comment]
The `startState` takes an object with two properties

1. `run` which is a function that runs when the state is active.
2. `next` which links user to the next state depending on the input.

Yours doesn't have a run... Check the example on the Readme

**Comment by Wanyeki** [comment]
why would you want a `startState` without a run?

**Comment by AsetaShadrach** [comment]
I chose to have it us such because of the explanation detailed in the  docs in case I don't have an actual `run` function

This section:
`If the start state does not define a run method, you provide an empty string as key in next to redirect to another state.`

If want to determine a start-state based on say a users credentials. Having if checks in the `run` function casues the startstae to always be checked
e.g 

```
const user = await getUser(phoneNumber);
menu.startState({
    next: {
        '': function(){
            if(user.isRegistered && user.isActive){
                return 'userMenu';
            }else if(user.isActive && user.isActive){
                return 'activationMenu';
            }else{
                return 'registerMenu';
            }
        }
    }
});
```


Also, it only accounts for service short-codes that we can't append text. e.g `*100#` will work okay but if you want to use `*100*01#` to run/return a different menu, it will skip the next menu because it reads the `01` as input-text for the next menu even if it is in the inital code you dial.
